version: '3.9'

services:
  postgres:
    image: postgres:14
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin1admin1'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh

  minio:
    image: minio/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: 'admin'
      MINIO_ROOT_PASSWORD: 'admin1admin1'
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  minio-client:
    image: minio/mc
    depends_on:
      - minio
    volumes:
      - ./minio/create-bucket.sh:/entrypoint/create-bucket.sh
    entrypoint: >
      /bin/sh -c "cd /entrypoint && /bin/sh ./create-bucket.sh"

  nginx:
    image: nginx:1.24-bullseye
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '8080:8080'
      - '8081:8081'

volumes:
  minio_data:
  postgres_data:
